//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingClub.ModelsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Class { get; set; }
        public decimal Amount { get; set; }
        public int NumberOfStudents { get; set; }
        public decimal TotalAmount { get; set; }
        public string Category { get; set; }
        public string UserId { get; set; }
        public int ProgramID { get; set; }
    }
}
