//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingClub.ModelsDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RaceDBEntities : DbContext
    {
        public RaceDBEntities()
            : base("name=RaceDBEntities")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }

        public virtual DbSet<Program> Programs { get; set; }

        public virtual DbSet<Booking> Bookings { get; set; }

        public System.Data.Entity.DbSet<TrainingClub.Models.BookingViewModel> BookingViewModels { get; set; }
    }
}
