//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingClub.ModelsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public int Id { get; set; }
        public string ProgramName { get; set; }
        public decimal ProgramFee { get; set; }
        public int NumberOfStudents { get; set; }
        public string Description { get; set; }
    }
}
